### Get all products
GET http://localhost:3000/products

### Get product by ID
GET http://localhost:3000/products/690c17fd5633cdf86dfa1cdc

### Create product
POST http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMxNjIzN2Q4ZjA2YjRjNTljODY3MyIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDFAZXhhbXBsZS5jb20iLCJyb2wiOiJBRE1JTiIsImlhdCI6MTc2MjQwMTI0OCwiZXhwIjoxNzY0OTkzMjQ4fQ.mFrp8wcymzruDzBy4JCXwvxpCb5-rLrz-TSZ1UKJ0KQ
Content-Type: application/json

{
  "nombre": "Televisor",
  "descripcion": "Laptop de alta performance",
  "precio": 1200.00,
  "stock": 10,
  "marca": "Dell",
  "categoria": "690c17fd5633cdf86dfa1cdc"
}

### Update product
PUT http://localhost:3000/products/690c17fd5633cdf86dfa1cdc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMxNjIzN2Q4ZjA2YjRjNTljODY3MyIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDFAZXhhbXBsZS5jb20iLCJyb2wiOiJBRE1JTiIsImlhdCI6MTc2MjQwMDYwOSwiZXhwIjoxNzY0OTkyNjA5fQ.1eAOarG7F1FHVenkpO50dnQeNeu82o9vINNQb9AxzF4
Content-Type: application/json

{
  "nombre": "Laptop Dell XPS",
  "descripcion": "Laptop de ultra alta performance",
  "precio": 1500.00,
  "stock": 15,
  "marca": "Dell"
}

### Delete product
DELETE http://localhost:3000/products/690c17fd5633cdf86dfa1cdc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMxNjIzN2Q4ZjA2YjRjNTljODY3MyIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDFAZXhhbXBsZS5jb20iLCJyb2wiOiJBRE1JTiIsImlhdCI6MTc2MjQwMDQ5NiwiZXhwIjoxNzY0OTkyNDk2fQ.X2wpQ7rbuUPnzlHlGmxfGobVmV371Z5eC8xPMrUZnx4

### Get products by category
GET http://localhost:3000/products?categoria=690c17fd5633cdf86dfa1cdc