### Create cart for user
POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMzYjg4YTBmMDkwMGM2MjFmM2M0YSIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDJAZXhhbXBsZS5jb20iLCJyb2wiOiJDTElFTlQiLCJpYXQiOjE3NjI0MDk0NzksImV4cCI6MTc2NTAwMTQ3OX0.L5c_aA7SPBJxB-19DNIIpbAl1JS0ii8Il8TGOr3G8wk

{
  "userId": "690c3b88a0f0900c621f3c4a"
}

###
### Get cart for user
GET http://localhost:3000/cart/user/690c3b88a0f0900c621f3c4a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMzYjg4YTBmMDkwMGM2MjFmM2M0YSIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDJAZXhhbXBsZS5jb20iLCJyb2wiOiJDTElFTlQiLCJpYXQiOjE3NjI0MDk0NzksImV4cCI6MTc2NTAwMTQ3OX0.L5c_aA7SPBJxB-19DNIIpbAl1JS0ii8Il8TGOr3G8wk

###
### Add product to cart
PUT http://localhost:3000/cart/CART_ID_HERE
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMzYjg4YTBmMDkwMGM2MjFmM2M0YSIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDJAZXhhbXBsZS5jb20iLCJyb2wiOiJDTElFTlQiLCJpYXQiOjE3NjI0MDk0NzksImV4cCI6MTc2NTAwMTQ3OX0.L5c_aA7SPBJxB-19DNIIpbAl1JS0ii8Il8TGOr3G8wk

{
  "producto": "690c17fd5633cdf86dfa1cdc",
  "cantidad": 2
}

###
### Delete cart
DELETE http://localhost:3000/cart/CART_ID_HERE
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGMzYjg4YTBmMDkwMGM2MjFmM2M0YSIsIm5vbWJyZSI6IkV6ZXF1aWVsIEdvbnphbGV6IiwiZW1haWwiOiJlemVxdWllbDJAZXhhbXBsZS5jb20iLCJyb2wiOiJDTElFTlQiLCJpYXQiOjE3NjI0MDk0NzksImV4cCI6MTc2NTAwMTQ3OX0.L5c_aA7SPBJxB-19DNIIpbAl1JS0ii8Il8TGOr3G8wk